-- Seed: orders

TRUNCATE TABLE orders CASCADE;

INSERT INTO orders (items) VALUES
  (ARRAY['Cheese', 'Milk', 'Potatoes', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Salt', 'Tea Powder']),
  (ARRAY['Coffee', 'Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Dal', 'Milk', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Bread', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Ketchup', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Jam', 'Ketchup', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Soda', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Peanut Butter', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Cooking Soda', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Onions', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Dal', 'Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Coriander Powder', 'Milk', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Corn Flakes', 'Milk', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Bread', 'Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Mixed Fruit Jam', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Cumin Seeds', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Milk', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Salt', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Eggs', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coconut Oil', 'Dal', 'Milk', 'Tea Powder']),
  (ARRAY['Dal', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Ketchup', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Onions', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Corn Flakes', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Chili Powder', 'Cream', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Mixed Fruit Jam', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Bread', 'Cooking Oil', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Chili Powder', 'Corn Flakes', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cumin Seeds', 'Dal', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Ketchup', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Soda', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Maggi Noodles', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Ketchup', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Maggi Noodles', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Ketchup', 'Milk', 'Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cream', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Green Tea', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Maggi Noodles', 'Milk', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Potatoes', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Mixed Fruit Jam', 'Sugar', 'Tea Powder']),
  (ARRAY['Onions', 'Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Honey', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Corn Flakes', 'Sugar', 'Tea Powder']),
  (ARRAY['Coriander Powder', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cumin Seeds', 'Tea Powder']),
  (ARRAY['Cream', 'Honey', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cream', 'Milk', 'Rice', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cheese', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Onions', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Peanut Butter', 'Sugar', 'Tea Powder', 'Turmeric Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Green Tea', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cheese', 'Potatoes', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cheese', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cheese', 'Maggi Noodles', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Tea Powder', 'Turmeric Powder']),
  (ARRAY['Coffee', 'Mixed Fruit Jam', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Dal', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Onions', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Corn Flakes', 'Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Rice', 'Tea Powder', 'Turmeric Powder']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Cooking Oil', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Bread', 'Eggs', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Tea Powder']),
  (ARRAY['Milk', 'Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cream', 'Green Tea', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Soda', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Soda', 'Green Tea', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Butter', 'Honey', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Mixed Fruit Jam', 'Onions', 'Tea Powder']),
  (ARRAY['Bread', 'Coconut Oil', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Butter', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Honey', 'Milk', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Dal', 'Sugar', 'Tea Powder', 'Turmeric Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Milk', 'Tea Powder']),
  (ARRAY['Cooking Soda', 'Cream', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Bread', 'Milk', 'Tea Powder']),
  (ARRAY['Cream', 'Maggi Noodles', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Ketchup', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Mixed Fruit Jam', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Soda', 'Milk', 'Tea Powder']),
  (ARRAY['Butter', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Green Tea', 'Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Maggi Noodles', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Coriander Powder', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Dal', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cream', 'Milk', 'Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Butter', 'Milk', 'Peanut Butter', 'Tea Powder']),
  (ARRAY['Maggi Noodles', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Dal', 'Peanut Butter', 'Tea Powder']),
  (ARRAY['Chili Powder', 'Coffee', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Eggs', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Rice', 'Tea Powder']),
  (ARRAY['Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coconut Oil', 'Jam', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Ketchup', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Cooking Soda', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Sugar', 'Tea Powder']),
  (ARRAY['Eggs', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Maggi Noodles', 'Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Dal', 'Jam', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Coconut Oil', 'Milk', 'Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Chili Powder', 'Milk', 'Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Chili Powder', 'Maggi Noodles', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coconut Oil', 'Coriander Powder', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Honey', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Potatoes', 'Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Peanut Butter', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Corn Flakes', 'Milk', 'Sugar', 'Tea Powder', 'Turmeric Powder']),
  (ARRAY['Cooking Oil', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Eggs', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Maggi Noodles', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Milk', 'Tea Powder']),
  (ARRAY['Biscuits', 'Salt', 'Sugar', 'Tea Powder']),
  (ARRAY['Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Biscuits', 'Butter', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Jam', 'Milk', 'Mixed Fruit Jam', 'Sugar']),
  (ARRAY['Coffee', 'Dal', 'Milk', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Onions', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Potatoes', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Peanut Butter', 'Sugar']),
  (ARRAY['Coffee', 'Honey', 'Milk', 'Onions', 'Sugar']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Corn Flakes', 'Sugar']),
  (ARRAY['Coffee', 'Coriander Powder', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Cumin Seeds', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Jam', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Maggi Noodles', 'Milk', 'Sugar']),
  (ARRAY['Butter', 'Coffee', 'Cream', 'Milk']),
  (ARRAY['Cheese', 'Coffee', 'Dal', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Potatoes', 'Rice', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Jam', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Rice', 'Sugar']),
  (ARRAY['Chili Powder', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Salt', 'Sugar', 'Turmeric Powder']),
  (ARRAY['Butter', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Onions', 'Potatoes', 'Sugar']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Onions', 'Sugar']),
  (ARRAY['Bread', 'Cheese', 'Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Dal', 'Salt', 'Sugar']),
  (ARRAY['Biscuits', 'Butter', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Corn Flakes', 'Cream', 'Milk', 'Salt']),
  (ARRAY['Coffee', 'Cumin Seeds', 'Jam', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Corn Flakes', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Peanut Butter', 'Sugar']),
  (ARRAY['Butter', 'Coffee', 'Honey', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Butter', 'Coffee', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Salt', 'Sugar']),
  (ARRAY['Coffee', 'Coriander Powder', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar', 'Turmeric Powder']),
  (ARRAY['Coffee', 'Milk', 'Onions', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Eggs', 'Milk', 'Sugar']),
  (ARRAY['Cheese', 'Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Jam', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Sugar']),
  (ARRAY['Butter', 'Coffee', 'Milk', 'Salt']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Rice', 'Sugar']),
  (ARRAY['Cheese', 'Coffee', 'Milk']),
  (ARRAY['Cheese', 'Coconut Oil', 'Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Potatoes', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Sugar']),
  (ARRAY['Coffee', 'Coriander Powder', 'Ketchup', 'Milk', 'Sugar']),
  (ARRAY['Chili Powder', 'Coffee', 'Cream', 'Jam', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Eggs', 'Peanut Butter', 'Sugar']),
  (ARRAY['Coffee', 'Coriander Powder', 'Cream', 'Rice']),
  (ARRAY['Coffee', 'Cooking Soda', 'Cream', 'Milk', 'Peanut Butter', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Onions', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Cream']),
  (ARRAY['Coconut Oil', 'Coffee', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Cheese', 'Coffee', 'Milk', 'Onions', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Cream', 'Peanut Butter', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Onions', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Bread', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coconut Oil', 'Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coconut Oil', 'Coffee', 'Milk']),
  (ARRAY['Coffee', 'Cooking Oil', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Cumin Seeds', 'Turmeric Powder']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Rice', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Cheese', 'Coffee', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Butter', 'Cheese', 'Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Cream', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Cream', 'Onions', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Ketchup', 'Milk']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Soda', 'Milk', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Coriander Powder', 'Rice', 'Sugar']),
  (ARRAY['Coffee', 'Dal', 'Ketchup', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Honey', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Onions', 'Potatoes']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cumin Seeds', 'Milk', 'Sugar', 'Turmeric Powder']),
  (ARRAY['Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Dal', 'Milk', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Milk']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Coriander Powder', 'Milk', 'Potatoes', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Sugar']),
  (ARRAY['Chili Powder', 'Coffee', 'Coriander Powder', 'Cream', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Cooking Oil', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coconut Oil', 'Coffee', 'Cream', 'Milk', 'Potatoes', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Maggi Noodles', 'Milk', 'Salt']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Turmeric Powder']),
  (ARRAY['Coffee', 'Cream', 'Peanut Butter', 'Salt']),
  (ARRAY['Coffee', 'Cooking Oil', 'Milk', 'Salt']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Chili Powder', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Ketchup', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Mixed Fruit Jam', 'Peanut Butter']),
  (ARRAY['Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cumin Seeds', 'Green Tea', 'Milk', 'Sugar']),
  (ARRAY['Coconut Oil', 'Coffee', 'Cooking Soda', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Ketchup', 'Rice', 'Sugar']),
  (ARRAY['Biscuits', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Cream']),
  (ARRAY['Coffee', 'Cooking Soda', 'Cream', 'Ketchup', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Salt', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Soda', 'Milk', 'Salt']),
  (ARRAY['Bread', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Eggs', 'Milk', 'Sugar']),
  (ARRAY['Coconut Oil', 'Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coconut Oil', 'Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Soda', 'Milk', 'Onions']),
  (ARRAY['Coffee', 'Onions', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Cooking Soda', 'Milk']),
  (ARRAY['Butter', 'Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Oil', 'Cream', 'Sugar', 'Tea Powder']),
  (ARRAY['Coffee', 'Cream', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Eggs', 'Milk', 'Salt']),
  (ARRAY['Coffee', 'Coriander Powder', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Dal', 'Milk', 'Potatoes', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Soda', 'Corn Flakes', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Potatoes']),
  (ARRAY['Biscuits', 'Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Dal', 'Milk']),
  (ARRAY['Cheese', 'Coffee', 'Milk', 'Tea Powder']),
  (ARRAY['Bread', 'Coffee', 'Coriander Powder', 'Cream', 'Milk']),
  (ARRAY['Coffee', 'Cooking Soda', 'Milk']),
  (ARRAY['Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Butter', 'Coffee', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Butter', 'Coffee', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Cheese', 'Coffee', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Soda', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cream', 'Cumin Seeds', 'Milk', 'Sugar', 'Turmeric Powder']),
  (ARRAY['Coffee', 'Dal', 'Maggi Noodles', 'Milk']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk']),
  (ARRAY['Coffee', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Coriander Powder', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Coffee', 'Cooking Oil', 'Cooking Soda', 'Cream', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Coffee']),
  (ARRAY['Bread', 'Butter', 'Cheese', 'Coconut Oil']),
  (ARRAY['Bread', 'Butter', 'Maggi Noodles']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Milk', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Rice']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Cooking Soda', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Ketchup', 'Tea Powder']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Green Tea', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Maggi Noodles']),
  (ARRAY['Bread', 'Butter', 'Cumin Seeds', 'Eggs', 'Milk']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Corn Flakes', 'Eggs', 'Jam', 'Mixed Fruit Jam']),
  (ARRAY['Bread', 'Butter', 'Rice', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Milk', 'Rice']),
  (ARRAY['Bread', 'Butter', 'Mixed Fruit Jam']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Corn Flakes']),
  (ARRAY['Bread', 'Cream', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Ketchup', 'Tea Powder']),
  (ARRAY['Bread', 'Jam', 'Mixed Fruit Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Eggs', 'Honey']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Green Tea', 'Sugar']),
  (ARRAY['Bread', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coconut Oil', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Sugar']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Ketchup', 'Turmeric Powder']),
  (ARRAY['Bread', 'Butter', 'Cheese', 'Dal', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Ketchup', 'Salt']),
  (ARRAY['Bread', 'Cream', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cumin Seeds', 'Salt']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Cooking Soda', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Ketchup']),
  (ARRAY['Bread', 'Eggs', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Eggs', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Salt']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Honey', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Onions', 'Rice']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Maggi Noodles']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Jam', 'Milk']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Salt']),
  (ARRAY['Bread', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Sugar']),
  (ARRAY['Bread', 'Jam']),
  (ARRAY['Bread', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Eggs', 'Milk']),
  (ARRAY['Bread', 'Cooking Soda', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Corn Flakes', 'Eggs', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Coffee', 'Jam', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Cheese', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Corn Flakes', 'Eggs']),
  (ARRAY['Bread', 'Cream', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Onions']),
  (ARRAY['Bread', 'Butter', 'Chili Powder', 'Cooking Soda', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cream', 'Cumin Seeds']),
  (ARRAY['Bread', 'Chili Powder', 'Eggs', 'Jam', 'Milk']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Cheese', 'Eggs', 'Milk']),
  (ARRAY['Bread', 'Butter', 'Coconut Oil', 'Corn Flakes']),
  (ARRAY['Bread', 'Butter', 'Chili Powder', 'Eggs']),
  (ARRAY['Bread', 'Cumin Seeds', 'Eggs', 'Jam', 'Potatoes']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Salt']),
  (ARRAY['Biscuits', 'Bread', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cumin Seeds', 'Milk']),
  (ARRAY['Bread', 'Butter', 'Salt']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Honey', 'Jam', 'Salt']),
  (ARRAY['Bread', 'Coffee', 'Jam', 'Milk']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Jam', 'Milk']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Jam', 'Potatoes', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Coriander Powder', 'Eggs', 'Jam', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Onions']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Coriander Powder', 'Cream', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cheese']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Mixed Fruit Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Sugar']),
  (ARRAY['Biscuits', 'Bread', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Salt']),
  (ARRAY['Bread', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda', 'Eggs', 'Mixed Fruit Jam']),
  (ARRAY['Biscuits', 'Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Potatoes']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Maggi Noodles']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda', 'Eggs', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Cream', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Tea Powder']),
  (ARRAY['Bread', 'Coffee', 'Eggs', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Honey', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Eggs', 'Sugar']),
  (ARRAY['Bread', 'Cooking Soda', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Cheese']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Eggs', 'Salt']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Cheese', 'Jam', 'Ketchup']),
  (ARRAY['Bread', 'Butter', 'Green Tea', 'Potatoes']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Eggs', 'Jam', 'Salt']),
  (ARRAY['Bread', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coriander Powder', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Cream', 'Peanut Butter']),
  (ARRAY['Bread', 'Butter', 'Corn Flakes', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Coriander Powder', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Peanut Butter']),
  (ARRAY['Bread', 'Butter', 'Salt']),
  (ARRAY['Bread', 'Cheese', 'Cream', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Cream', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Peanut Butter', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Cumin Seeds']),
  (ARRAY['Bread', 'Eggs', 'Sugar', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Milk', 'Peanut Butter']),
  (ARRAY['Bread', 'Butter', 'Corn Flakes', 'Ketchup']),
  (ARRAY['Bread', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Jam']),
  (ARRAY['Bread', 'Coffee', 'Eggs', 'Jam', 'Potatoes']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Eggs', 'Jam', 'Potatoes']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Rice']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Eggs', 'Milk']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Salt']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Cumin Seeds']),
  (ARRAY['Bread', 'Cheese', 'Coffee', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Biscuits', 'Bread', 'Butter', 'Jam', 'Potatoes']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Potatoes']),
  (ARRAY['Bread', 'Butter', 'Corn Flakes', 'Eggs', 'Green Tea', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Coffee', 'Eggs', 'Jam', 'Sugar']),
  (ARRAY['Bread', 'Butter', 'Cumin Seeds', 'Eggs', 'Jam', 'Peanut Butter']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Honey', 'Jam', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Dal', 'Eggs']),
  (ARRAY['Bread', 'Cheese', 'Eggs']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Jam', 'Salt', 'Tea Powder']),
  (ARRAY['Bread', 'Butter', 'Chili Powder', 'Cooking Oil', 'Jam']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda', 'Dal', 'Jam']),
  (ARRAY['Bread', 'Eggs', 'Jam', 'Potatoes']),
  (ARRAY['Bread', 'Butter']),
  (ARRAY['Bread', 'Butter', 'Mixed Fruit Jam']),
  (ARRAY['Bread', 'Butter', 'Green Tea']),
  (ARRAY['Bread', 'Coffee', 'Cooking Soda', 'Jam']),
  (ARRAY['Bread', 'Cooking Soda', 'Eggs']),
  (ARRAY['Bread', 'Butter', 'Cooking Soda']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Green Tea', 'Rice']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Eggs', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice', 'Sugar']),
  (ARRAY['Dal', 'Milk', 'Onions', 'Rice', 'Salt']),
  (ARRAY['Cooking Oil', 'Dal', 'Ketchup', 'Rice', 'Salt']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Jam', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Peanut Butter', 'Potatoes', 'Rice']),
  (ARRAY['Bread', 'Cooking Oil', 'Dal', 'Mixed Fruit Jam', 'Rice']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Butter', 'Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Corn Flakes', 'Dal', 'Eggs', 'Rice']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Honey', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Maggi Noodles', 'Rice']),
  (ARRAY['Corn Flakes', 'Cumin Seeds', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Soda', 'Dal', 'Ketchup', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Eggs', 'Rice']),
  (ARRAY['Dal', 'Honey', 'Onions', 'Rice', 'Salt']),
  (ARRAY['Cream', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Bread', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Butter', 'Cheese', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Bread', 'Coffee', 'Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Mixed Fruit Jam', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Milk', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Dal', 'Potatoes', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Cheese', 'Cream', 'Onions', 'Rice']),
  (ARRAY['Butter', 'Cooking Oil', 'Dal', 'Onions', 'Potatoes', 'Rice']),
  (ARRAY['Corn Flakes', 'Dal', 'Green Tea', 'Rice']),
  (ARRAY['Biscuits', 'Dal', 'Onions', 'Potatoes', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Dal', 'Onions', 'Rice', 'Turmeric Powder']),
  (ARRAY['Dal', 'Green Tea', 'Onions', 'Rice']),
  (ARRAY['Butter', 'Cooking Oil', 'Corn Flakes', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Eggs', 'Honey', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Green Tea', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Jam', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Biscuits', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Jam', 'Onions', 'Rice']),
  (ARRAY['Coffee', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Butter', 'Corn Flakes', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Butter', 'Cheese', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Potatoes', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Dal', 'Green Tea', 'Onions', 'Rice']),
  (ARRAY['Butter', 'Dal', 'Jam', 'Rice']),
  (ARRAY['Cheese', 'Cooking Oil', 'Rice']),
  (ARRAY['Biscuits', 'Dal', 'Ketchup', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Bread', 'Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Butter', 'Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Coconut Oil', 'Dal', 'Green Tea', 'Rice']),
  (ARRAY['Dal', 'Jam', 'Rice', 'Sugar']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Mixed Fruit Jam', 'Rice']),
  (ARRAY['Butter', 'Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Cream', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Bread', 'Coriander Powder', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cream', 'Dal', 'Onions', 'Potatoes', 'Rice']),
  (ARRAY['Cooking Oil', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Onions', 'Rice', 'Sugar']),
  (ARRAY['Dal', 'Honey', 'Rice']),
  (ARRAY['Dal', 'Maggi Noodles', 'Onions', 'Rice']),
  (ARRAY['Cooking Soda', 'Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Cream', 'Dal', 'Eggs', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Dal', 'Green Tea', 'Peanut Butter', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Milk', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Onions', 'Rice', 'Sugar']),
  (ARRAY['Biscuits', 'Dal', 'Honey', 'Rice']),
  (ARRAY['Biscuits', 'Coffee', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Corn Flakes', 'Dal', 'Rice']),
  (ARRAY['Biscuits', 'Dal', 'Honey', 'Onions', 'Rice']),
  (ARRAY['Bread', 'Onions', 'Rice']),
  (ARRAY['Bread', 'Corn Flakes', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Eggs', 'Green Tea', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Cumin Seeds', 'Mixed Fruit Jam', 'Onions', 'Rice']),
  (ARRAY['Cooking Soda', 'Cream', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Cheese', 'Chili Powder', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Cream', 'Dal', 'Rice']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Corn Flakes', 'Dal', 'Rice']),
  (ARRAY['Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Chili Powder', 'Coconut Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Onions', 'Rice', 'Sugar']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Corn Flakes', 'Dal', 'Rice']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Soda', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Peanut Butter', 'Rice', 'Sugar']),
  (ARRAY['Cooking Oil', 'Eggs', 'Rice', 'Sugar']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice', 'Turmeric Powder']),
  (ARRAY['Chili Powder', 'Cooking Oil', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Cheese', 'Cooking Oil', 'Rice']),
  (ARRAY['Cooking Oil', 'Onions', 'Peanut Butter', 'Rice']),
  (ARRAY['Butter', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Cheese', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Rice']),
  (ARRAY['Chili Powder', 'Dal', 'Onions', 'Peanut Butter', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Milk', 'Rice']),
  (ARRAY['Dal', 'Rice', 'Sugar']),
  (ARRAY['Cooking Oil', 'Rice', 'Sugar']),
  (ARRAY['Dal', 'Eggs', 'Maggi Noodles', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice', 'Salt']),
  (ARRAY['Dal', 'Milk', 'Onions', 'Rice']),
  (ARRAY['Bread', 'Onions', 'Rice']),
  (ARRAY['Coriander Powder', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Peanut Butter', 'Rice']),
  (ARRAY['Coffee', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Rice', 'Sugar', 'Tea Powder']),
  (ARRAY['Butter', 'Corn Flakes', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Coconut Oil', 'Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Corn Flakes', 'Rice', 'Salt']),
  (ARRAY['Dal', 'Green Tea', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Butter', 'Cooking Oil', 'Dal', 'Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Dal', 'Eggs', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice', 'Salt']),
  (ARRAY['Coconut Oil', 'Dal', 'Honey', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Ketchup', 'Onions', 'Rice']),
  (ARRAY['Dal', 'Rice', 'Sugar']),
  (ARRAY['Cooking Oil', 'Cooking Soda', 'Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Cooking Oil', 'Onions', 'Peanut Butter', 'Rice']),
  (ARRAY['Dal', 'Rice']),
  (ARRAY['Bread', 'Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Butter', 'Cooking Oil', 'Maggi Noodles', 'Onions', 'Rice']),
  (ARRAY['Cooking Oil', 'Corn Flakes', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Green Tea', 'Rice', 'Sugar']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Dal', 'Onions', 'Rice']),
  (ARRAY['Onions', 'Rice']),
  (ARRAY['Biscuits', 'Cooking Oil', 'Dal', 'Milk', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Onions', 'Rice', 'Tea Powder', 'Turmeric Powder']),
  (ARRAY['Bread', 'Butter', 'Cooking Oil', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Rice', 'Tea Powder']),
  (ARRAY['Dal', 'Milk', 'Onions', 'Rice']),
  (ARRAY['Cheese', 'Dal', 'Rice']),
  (ARRAY['Cooking Oil', 'Dal', 'Maggi Noodles', 'Onions', 'Rice', 'Turmeric Powder']),
  (ARRAY['Onions', 'Rice', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coffee', 'Cooking Oil', 'Dal', 'Onions', 'Rice']),
  (ARRAY['Coffee', 'Cooking Oil', 'Rice']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Onions', 'Potatoes']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Potatoes']),
  (ARRAY['Cheese', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cooking Oil', 'Eggs', 'Maggi Noodles', 'Salt']),
  (ARRAY['Cheese', 'Coconut Oil', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Coconut Oil', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Bread', 'Cream', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Coriander Powder', 'Eggs', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cooking Soda', 'Eggs', 'Maggi Noodles', 'Onions']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Honey', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Eggs', 'Jam', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Coriander Powder', 'Cumin Seeds', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Bread', 'Cheese', 'Chili Powder', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Coffee', 'Cream', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Butter', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Mixed Fruit Jam']),
  (ARRAY['Cheese', 'Coffee', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Cream', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Cream', 'Cumin Seeds', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Maggi Noodles']),
  (ARRAY['Bread', 'Cheese', 'Coriander Powder', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Butter', 'Cream', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Coffee', 'Eggs', 'Maggi Noodles', 'Milk']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Coffee', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Turmeric Powder']),
  (ARRAY['Cheese', 'Coriander Powder', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Butter', 'Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Peanut Butter']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Salt']),
  (ARRAY['Cheese', 'Cream', 'Ketchup', 'Maggi Noodles', 'Milk']),
  (ARRAY['Eggs', 'Green Tea', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Eggs', 'Maggi Noodles', 'Milk']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Potatoes']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Chili Powder', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Green Tea', 'Maggi Noodles']),
  (ARRAY['Coffee', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Green Tea', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Bread', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Cooking Soda', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coffee', 'Eggs', 'Maggi Noodles', 'Milk']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Sugar', 'Tea Powder']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Bread', 'Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Butter', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Cheese', 'Eggs', 'Honey', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Cheese', 'Coconut Oil', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Butter', 'Cheese', 'Ketchup', 'Maggi Noodles', 'Potatoes']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Cumin Seeds', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Green Tea', 'Maggi Noodles', 'Potatoes']),
  (ARRAY['Honey', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Honey', 'Maggi Noodles', 'Peanut Butter']),
  (ARRAY['Cheese', 'Jam', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Dal', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Peanut Butter', 'Turmeric Powder']),
  (ARRAY['Cheese', 'Cooking Oil', 'Cream', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Corn Flakes', 'Dal', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Coffee', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Cooking Oil', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles', 'Mixed Fruit Jam']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Onions']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Rice']),
  (ARRAY['Cheese', 'Cream', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Potatoes']),
  (ARRAY['Cheese', 'Coriander Powder', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Bread', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Mixed Fruit Jam']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Coffee', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Coriander Powder', 'Eggs', 'Maggi Noodles', 'Rice']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Salt']),
  (ARRAY['Cheese', 'Eggs', 'Honey', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Cheese', 'Chili Powder', 'Cooking Oil', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Dal', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coriander Powder', 'Ketchup', 'Maggi Noodles', 'Onions']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Milk']),
  (ARRAY['Biscuits', 'Cheese', 'Cream', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Bread', 'Cheese', 'Maggi Noodles', 'Rice']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Chili Powder', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Dal', 'Eggs', 'Jam', 'Maggi Noodles']),
  (ARRAY['Dal', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Onions']),
  (ARRAY['Cheese', 'Dal', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Jam', 'Maggi Noodles', 'Onions']),
  (ARRAY['Butter', 'Cumin Seeds', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Coffee', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Cheese', 'Honey', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Cheese', 'Corn Flakes', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Milk', 'Turmeric Powder']),
  (ARRAY['Cumin Seeds', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cooking Oil', 'Eggs', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Bread', 'Coconut Oil', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Cream', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Potatoes']),
  (ARRAY['Bread', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Eggs', 'Honey', 'Jam', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Onions']),
  (ARRAY['Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Milk']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Sugar', 'Tea Powder']),
  (ARRAY['Cheese', 'Coffee', 'Maggi Noodles', 'Milk']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Bread', 'Cheese', 'Chili Powder', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Coconut Oil', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Coffee', 'Maggi Noodles', 'Salt']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Milk']),
  (ARRAY['Butter', 'Cheese', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Sugar']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Coriander Powder', 'Ketchup', 'Maggi Noodles', 'Onions']),
  (ARRAY['Cheese', 'Coffee', 'Eggs', 'Maggi Noodles', 'Milk']),
  (ARRAY['Ketchup', 'Maggi Noodles', 'Salt']),
  (ARRAY['Cooking Oil', 'Eggs', 'Maggi Noodles', 'Peanut Butter']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Eggs', 'Honey', 'Maggi Noodles']),
  (ARRAY['Coriander Powder', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Cooking Soda', 'Maggi Noodles', 'Salt']),
  (ARRAY['Biscuits', 'Cheese', 'Coffee', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Butter', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Chili Powder', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Biscuits', 'Coriander Powder', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Green Tea', 'Ketchup', 'Maggi Noodles', 'Mixed Fruit Jam']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Peanut Butter', 'Tea Powder']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Coffee', 'Cumin Seeds', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Dal', 'Eggs', 'Ketchup', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Chili Powder', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Cheese', 'Eggs', 'Jam', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Bread', 'Butter', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Jam', 'Maggi Noodles', 'Tea Powder']),
  (ARRAY['Coffee', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Chili Powder', 'Coffee', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Biscuits', 'Coffee', 'Eggs', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Green Tea', 'Maggi Noodles']),
  (ARRAY['Chili Powder', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Ketchup', 'Maggi Noodles']),
  (ARRAY['Coconut Oil', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Cheese', 'Coriander Powder', 'Corn Flakes', 'Eggs', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Butter', 'Coffee', 'Ketchup', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles']),
  (ARRAY['Eggs', 'Maggi Noodles', 'Rice', 'Sugar']);
